---
- name: configuring tomcat
  hosts: all
  tasks:
    - name: install tomcat9
      apt:
        name: tomcat9
        state: present
    - name: install tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
    - name: change port of tomcat 9090 to 8080
      replace:
        regexp: 9090
        replace: 8080
        path: /etc/tomcat9/server.xml
    - name: restart tomcat
      service:
        name: tomcat9
        state: restarted
    - name: check tomcat response on server1
      uri:
        url: http://172.31.14.43
        status_code: 200
    - name: check tomcat response on server2
      uri:
        url: http://172.31.5.218
        status_code: 200
        
