---
- name: create users and create files/directories in user home dir
  hosts: all
  tasks:
    - name: create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create files/dirs in user home dir
      file:
        name: "{{d}}"
        state: "{{e}}"
...
