---
- name: install/uninstall s/w's
  hosts: all
  tasks:
    - name: install/uninstall s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: absent,c: no}
        - {a: git,b: present,c: no}
        - {a: maven,b: latest,c: no}
...
