---
- name: capture os info
  hosts: all
  tasks:
    - name: display os name
      debug: msg="{{ansible_distribution}}"
    - name: display os version
      debug: msg="{{ansible_distribution_version}}"
    - name: display os major version
      debug: msg="{{ansible_distribution_major_version}}"
...
