---
- name: install/uninstall s/w's 
  hosts: all
  vars:
    - a: tomcat9
    - b: present
    - c: no
  tasks:
    - name: install tomcat9
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
